apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: backend-rules
  labels:
    release: prometheus
spec:
  groups:
    - name: backend-alerts
      rules:
        - alert: BackendDown
          expr: up{job="backend-service"} == 0
          for: 2s
          labels:
            severity: critical
          annotations:
            summary: "backend instance down"
            description: "The  backend instance is down for more than 5 minutes."
        - alert: HighRequestLatency
          expr: http_request_duration_seconds{job="backend-service", quantile="0.99"} > 1
          for: 1s
          labels:
            severity: warning
          annotations:
            summary: "High request latency"
            description: "Request latency is above 1 second for the backend."
        - alert: AlwaysFiringAlerting
          expr: vector(1)  
          labels:
            severity: critical
            name : AlwaysFiring
          annotations:
            summary: "Always firing alert"
            description: "This alert rule always triggers as its condition is constantly true."



---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  labels:
    resource: prometheus
    release: prometheus
spec:
  receivers:
    - name: webhook
      webhookConfigs:
        - url: http://10.152.183.139/alerts

  route:
    groupBy: ['severity']
    groupInterval: 5s
    groupWait: 10s
    receiver: webhook
    repeatInterval: 30s
    routes:
      - matchers:
          - name: alertname
            value: AlwaysFiringAlerting
        receiver: webhook
