apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  labels:
    app: alertmanager
    resource: prometheus
spec:
  route:
    groupBy: ['severity']
    groupInterval: 5m
    groupWait: 30s
    repeatInterval: 12h
    routes:
      - match:
          severity: critical
        receiver: webhook

  receivers:
    - name: webhook
      webhookConfigs:
        - url: 'http://10.152.183.236/alerts'
