apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mohammedaabouche/backend:2.0
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-password
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb-service

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
    job: backend-service
spec:
  selector:
    app: backend
  ports:
    - name: backend-port
      protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-service-monitor
  labels:
    release: prometheus
spec:
  jobLabel: job
  selector:
    matchLabels:
      job: backend-service
  endpoints:
    - port: backend-port
      interval: 30s
      path: /swagger-stats/metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: backend-prometheus-rule
  labels:
    release: prometheus
spec:
  groups:
    - name: backend
      rules:
        - alert: FewRequestsAlert
          expr: http_requests_total{job="your-job"} < 5
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: Few HTTP requests
            description: Fewer than 5 HTTP 
      