apiVersion:  apps/v1
kind: Deployment
metadata:
  name: nestjs-deployment
  labels:
    app: nestjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
        - name: nestjs
          image: mohammedaabouche/nestjs:1.0
          ports:
            - containerPort: 3000
        