apiVersion:  apps/v1
kind: Deployment
metadata:
  name: nestjs-deployment
  labels:
    app: nestjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
        - name: nestjs
          image: mohammedaabouche/nestjs:3.2
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-service
spec:
  selector:
    app: nestjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  

